version: '2'
services:
  web:
    build: .
    ports:
     - "4500:4500"
    volumes:
     - .:/var/www/app/current
  mongo:
    image: "mongo"
    ports:
     - "27017:27017"
  nginx:
    image: "nginx"
 